# fly.toml app configuration file generated for crypto-telegram-bot-lively-thunder-1411 on 2025-08-23T17:52:40+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crypto-telegram-bot-lively-thunder-1411"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  HOST = "0.0.0.0"
  PORT = "5555"

[deploy]
  # Apply Prisma migrations on each deploy against Supabase
  release_command = "npx prisma migrate deploy"

[http_service]
  internal_port = 5555
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout  = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
